
server:
  port: 8761
eureka:
  instance:
    hostname: 39.107.113.108
  client:
    register-with-eureka: false
    fetch-registry: false
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
